spring.application.name=reminderbot
discord.token=${DISCORD_TOKEN}


### Rabbit MQ ###
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.rabbitmq.marking-register.reply-timeout=30000
